version: "3.9"

services:
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - job-board-network

  database:
    container_name: postgres
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - job-board-network

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - job-board-network

  # backend:
  #   container_name: backend
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - database
  #   networks:
  #     - job-board-network

networks:
  job-board-network:
